/**
 * Copyright (c) 2024 DAZKON SOLUTIONS (DAZKON PVT LTD)
 * All rights reserved. 
 * This code is proprietary to DAZKON SOLUTIONS. 
 * Unauthorized use, reproduction, modification, distribution, or sale
 * without the explicit written permission of DAZKON SOLUTIONS is strictly prohibited.
 * For inquiries, please contact: info@dazkonsolutions.com
 */

export enum Permission {
  DEFAULT = 'DEFAULT',

  VIEW_DASHBOARD = 'VIEW_DASHBOARD',

  // Products --------------------------
  VIEW_PRODUCTS_SECTION = 'VIEW_PRODUCTS_SECTION',

  VIEW_PRODUCT_LIST_PAGE = 'VIEW_PRODUCT_LIST_PAGE',
  VIEW_PRODUCT = 'VIEW_PRODUCT',
  CAN_CREATE_PRODUCT = 'CAN_CREATE_PRODUCT',
  CAN_UPDATE_PRODUCT = 'CAN_UPDATE_PRODUCT',
  CAN_DELETE_PRODUCT = 'CAN_DELETE_PRODUCT',
  
  VIEW_BRAND_LIST_PAGE = 'VIEW_BRAND_LIST_PAGE',
  VIEW_BRAND = 'VIEW_BRAND',
  CAN_CREATE_BRAND = 'CAN_CREATE_BRAND',
  CAN_UPDATE_BRAND = 'CAN_UPDATE_BRAND',
  CAN_DELETE_BRAND = 'CAN_DELETE_BRAND',

  VIEW_CATEGORY_LIST_PAGE = 'VIEW_CATEGORY_LIST_PAGE',
  VIEW_CATEGORY = 'VIEW_CATEGORY',
  CAN_CREATE_CATEGORY = 'CAN_CREATE_CATEGORY',
  CAN_UPDATE_CATEGORY = 'CAN_UPDATE_CATEGORY',
  CAN_DELETE_CATEGORY = 'CAN_DELETE_CATEGORY',

  // Configurations --------------------------
  VIEW_CONFIGURATIONS_SECTION = 'VIEW_CONFIGURATIONS_SECTION',

  VIEW_BANK_LIST_PAGE = 'VIEW_BANK_LIST_PAGE',
  VIEW_BANK = 'VIEW_BANK',
  CAN_CREATE_BANK = 'CAN_CREATE_BANK',
  CAN_UPDATE_BANK = 'CAN_UPDATE_BANK',
  CAN_DELETE_BANK = 'CAN_DELETE_BANK',

  // Expenses --------------------------
  VIEW_EXPENSES_SECTION = 'VIEW_EXPENSES_SECTION',

  VIEW_EXPENSE_TYPE_LIST_PAGE = 'VIEW_EXPENSE_TYPE_LIST_PAGE',
  VIEW_EXPENSE_TYPE = 'VIEW_EXPENSE_TYPE',
  CAN_CREATE_EXPENSE_TYPE = 'CAN_CREATE_EXPENSE_TYPE',
  CAN_UPDATE_EXPENSE_TYPE = 'CAN_UPDATE_EXPENSE_TYPE',
  CAN_DELETE_EXPENSE_TYPE = 'CAN_DELETE_EXPENSE_TYPE',


  // Sample -------------------------------
  VIEW_SAMPLE_LIST_PAGE = 'VIEW_SAMPLE_LIST_PAGE',
  VIEW_SAMPLE = 'VIEW_SAMPLE',
  CAN_CREATE_SAMPLE = 'CAN_CREATE_SAMPLE',
  CAN_UPDATE_SAMPLE = 'CAN_UPDATE_SAMPLE',
  CAN_DELETE_SAMPLE = 'CAN_DELETE_SAMPLE',
}